# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='User',
        ),
    ]
